fix(*): update the workflow

diff --git a/.github/workflows/sync-translation.yml b/.github/workflows/sync-translation.yml
--- a/.github/workflows/sync-translation.yml
+++ b/.github/workflows/sync-translation.yml
@@ -48,64 +48,65 @@ jobs:
             sleep 60
           done
 
+      - name: Remove old translation files
+        run: |
+          FILE_PATH="src/assets/locale/messages.it.xlf"
+          if [ -f "$FILE_PATH" ]; then
+            rm "$FILE_PATH"
+            echo "Removed $FILE_PATH"
+          else
+            echo "File $FILE_PATH does not exist"
+          fi
+
       - name: Export translations from POEditor
         run: |
-          # languages=("en" "fr" "de" "it")
-          languages=("it")
-          # mkdir -p src/assets/translated/
-          for lang in "${languages[@]}"; do
-            echo "Exporting translations for language $lang"
-            response=$(curl -s -X POST https://api.poeditor.com/v2/projects/export \
-              -F "api_token=${{ secrets.POEDITOR_API_TOKEN }}" \
-              -F "id=${{ secrets.POEDITOR_PROJECT_ID }}" \
-              -F "language=$lang" \
-              -F "type=xlf")
-            status=$(echo $response | jq -r '.response.status')
+          lang="it"
+          response=$(curl -s -X POST https://api.poeditor.com/v2/projects/export \
+            -F "api_token=${{ secrets.POEDITOR_API_TOKEN }}" \
+            -F "id=${{ secrets.POEDITOR_PROJECT_ID }}" \
+            -F "language=$lang" \
+            -F "type=xlf")
+          status=$(echo $response | jq -r '.response.status')
 
-            FILE_PATH="src/assets/locale/messages.$lang.xlf"
-            if [ -f "$FILE_PATH" ]; then
-              rm "$FILE_PATH"
-              echo "File $FILE_PATH has been removed."
-            else
-              echo "File $FILE_PATH does not exist."
-            fi
-
-            if [ "$status" == "success" ]; then
-              url=$(echo $response | jq -r '.result.url')
-              if [ -n "$url" ]; then
-                echo "Downloading translations for $lang from $url"
-                curl -s -o src/assets/locale/messages.$lang.xlf $url
+          if [ "$status" == "success" ]; then
+            url=$(echo $response | jq -r '.result.url')
+            if [ -n "$url" ]; then
+              echo "Downloading translations for $lang from $url"
+              curl -s -o src/assets/locale/messages.$lang.xlf $url
                 if [ ! -f "src/assets/locale/messages.$lang.xlf" ]; then
                   echo "Failed to download translations for $lang"
                   exit 1
                 fi
-                echo "Downloaded translations for $lang"
-              else
-                echo "No URL found for downloading translations for $lang"
-                exit 1
-              fi
+              echo "Downloaded translations for $lang"
             else
-              echo "Error exporting translations for $lang: $response"
+              echo "No URL found for downloading translations for $lang"
               exit 1
             fi
-          done
-        shell: /usr/bin/bash -e {0}
+          else
+            echo "Error exporting translations for $lang: $response"
+            exit 1
+          fi
 
       - name: Configure Git
         run: |
           git config user.name ${{ secrets.GIT_USERNAME }}
           git config user.email ${{ secrets.GIT_EMAIL }}
           git remote set-url origin https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@${{ secrets.REPO_URL }}
+
       - name: Create new branch for translations
         run: |
           git checkout master
           git checkout -b update-translation-message
-          if git diff --quiet; then
-            echo "No changes to commit. Skipping PR creation."
+
+      - name: Stage and commit changes
+        run: |
+          git add src/assets/locale/*.xlf
+          if git diff --cached --quiet; then
+            echo "No changes to commit. Exiting."
             exit 0
           fi
-          git add src/assets/locale/*.xlf
           git commit -m "Update translations from POEditor"
+
       - name: Push changes
         run: git push origin update-translation-message
 
