fix(*): update workflow

diff --git a/.github/workflows/sync-translation.yml b/.github/workflows/sync-translation.yml
--- a/.github/workflows/sync-translation.yml
+++ b/.github/workflows/sync-translation.yml
@@ -1,4 +1,4 @@
-name: Update File Workflow
+name: Sync Translations with POEditor
 
 on:
   push:
@@ -10,25 +10,97 @@ permissions:
   pull-requests: write
 
 jobs:
-  update-file:
+  sync-translations:
     runs-on: ubuntu-latest
 
     steps:
-      # Step 1: Check out the repository
       - name: Checkout repository
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
 
-      # Step 2: Modify the file (overwrite content)
-      - name: Update file content
+      - name: Set up node
+        uses: actions/setup-node@v4
+
+      - name: Upload translations to POEditor
         run: |
-          echo "Ayush" > data.txt
+          declare -A files
+          # files["en"]="src/assets/locale/messages.xlf"
+          # files["fr"]="src/assets/locale/messages.fr.xlf"
+          # files["de"]="src/assets/locale/messages.de.xlf"
+          files["it"]="src/assets/locale/messages.it.xlf"
+          for lang in "${!files[@]}"; do
+            echo "Uploading ${files[$lang]} for language $lang"
+            response=$(curl -s -X POST https://api.poeditor.com/v2/projects/upload \
+              -F "api_token=56acaf6808f07eb52c5b39a3abea19a7" \
+              -F "id=740876" \
+              -F "language=$lang" \
+              -F "updating=terms_translations" \
+              -F "file=@${files[$lang]}")
+            status=$(echo $response | jq -r '.response.status')
+            if [ "$status" != "success" ]; then
+              echo "Error uploading file for $lang: $response"
+              exit 1
+            fi
+            echo "Waiting for 1 minute to respect rate limits..."
+            sleep 60
+          done
+      - name: Export and replace translations
+        run: |
+          languages=("it")
+          for lang in "${languages[@]}"; do
+            echo "Exporting translations for language $lang"
+            response=$(curl -s -X POST https://api.poeditor.com/v2/projects/export \
+              -F "api_token=56acaf6808f07eb52c5b39a3abea19a7" \
+              -F "id=740876" \
+              -F "language=$lang" \
+              -F "type=xlf")
+            status=$(echo $response | jq -r '.response.status')
+            if [ "$status" == "success" ]; then
+              url=$(echo $response | jq -r '.result.url')
+              if [ -n "$url" ]; then
+                echo "Downloading translations for $lang from $url"
+                curl -s -o temp_translations.xlf $url
+                if [ ! -f "temp_translations.xlf" ]; then
+                  echo "Failed to download translations for $lang"
+                  exit 1
+                fi
+                echo "Replacing content in the existing file for $lang"
+                cp temp_translations.xlf src/assets/locale/messages.$lang.xlf
+                rm temp_translations.xlf
+                echo "Replaced translations for $lang"
+              else
+                echo "No URL found for downloading translations for $lang"
+                exit 1
+              fi
+            else
+              echo "Error exporting translations for $lang: $response"
+              exit 1
+            fi
+          done
+        shell: /usr/bin/bash -e {0}
 
-      # Step 3: Commit and push the changes
-      - name: Commit and push changes
+      - name: Configure Git
         run: |
           git config user.name "Ayush8923"
           git config user.email "ayuuniyal7@gmail.com"
-          git remote set-url origin https://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@github.com/Ayush8923/POEditor-Workflow.git
-          git add data.txt
-          git commit -m "Update file via GitHub Actions"
-          git push
+          git remote set-url origin https://x-access-token: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@github.com/Ayush8923/POEditor-Workflow.git
+      - name: Create new branch for translations
+        run: |
+          git checkout master
+          git checkout -b update-translation-messages
+          if git diff --quiet; then
+            echo "No changes to commit. Skipping PR creation."
+            exit 0
+          fi
+          git add src/assets/translated/*.xlf
+          git commit -m "Update translations from POEditor"
+      - name: Push changes
+        run: git push origin update-translation-messages
+
+      - name: Create pull request
+        uses: peter-evans/create-pull-request@v5
+        with:
+          branch: update-translation-messages
+          base: master
+          title: "Update translations from POEditor"
+          body: |
+            This PR updates the translations exported from POEditor.
