fix(*): update the workflow

diff --git a/.github/workflows/sync-translation.yml b/.github/workflows/sync-translation.yml
--- a/.github/workflows/sync-translation.yml
+++ b/.github/workflows/sync-translation.yml
@@ -20,7 +20,7 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Set up node
+      - name: Set up Node.js
         uses: actions/setup-node@v4
 
       - name: Upload translations to POEditor
@@ -28,9 +28,10 @@ jobs:
           declare -A files
           # Populate file mappings dynamically
           # files["en"]="src/assets/locale/messages.en.xlf"
-          # files["fr"]="src/assets/locale/messages.fr.xlf"
           # files["de"]="src/assets/locale/messages.de.xlf"
-          files["it"]="src/assets/locale/messages.it.xlf"
+          # files["it"]="src/assets/locale/messages.it.xlf"
+
+          files["fr"]="src/assets/locale/messages.fr.xlf"
           for lang in "${!files[@]}"; do
             echo "Uploading ${files[$lang]} for language $lang"
             response=$(curl -s -X POST https://api.poeditor.com/v2/projects/upload \
@@ -48,6 +49,32 @@ jobs:
             sleep 60
           done
 
+      - name: Export translations from POEditor
+        run: |
+          languages=("fr")
+          for lang in "${languages[@]}"; do
+            echo "Exporting translations for language $lang"
+            response=$(curl -s -X POST https://api.poeditor.com/v2/projects/export \
+              -F "api_token=${{ secrets.POEDITOR_API_TOKEN }}" \
+              -F "id=${{ secrets.POEDITOR_PROJECT_ID }}" \
+              -F "language=$lang" \
+              -F "type=xlf")
+            status=$(echo $response | jq -r '.response.status')
+            if [ "$status" == "success" ]; then
+              url=$(echo $response | jq -r '.result.url')
+              if [ -n "$url" ]; then
+                echo "Downloading translations for $lang from $url"
+                curl -s -o src/assets/locale/messages.$lang.xlf $url
+              else
+                echo "No URL found for downloading translations for $lang"
+                exit 1
+              fi
+            else
+              echo "Error exporting translations for $lang: $response"
+              exit 1
+            fi
+          done
+
       - name: Configure Git
         run: |
           git config user.name ${{ secrets.GIT_USERNAME }}
@@ -56,77 +83,21 @@ jobs:
 
       - name: Create new branch for translations
         run: |
-          git checkout master
-          git checkout -b update-translation-message
-
-      - name: Remove old translation files
-        run: |
-          FILE_PATH="src/assets/locale/messages.it.xlf"
-          if [ -f "$FILE_PATH" ]; then
-            rm "$FILE_PATH"
-            echo "Removed $FILE_PATH"
-          else
-            echo "File $FILE_PATH does not exist"
-          fi
-
-      - name: Stage changes explicitly
-        run: |
-          echo "Staging updated translation files..."
-          git add -A
-          git status
-          if git diff --cached --quiet; then
-            echo "No changes detected. Exiting."
+          git checkout -b update-translations-$(date +%Y%m%d%H%M%S)
+          if git diff --quiet; then
+            echo "No changes to commit. Exiting."
             exit 0
           fi
-          git commit -m "delete existing translation files"
-
-      - name: Export translations from POEditor
-        run: |
-          lang="it"
-          response=$(curl -s -X POST https://api.poeditor.com/v2/projects/export \
-            -F "api_token=${{ secrets.POEDITOR_API_TOKEN }}" \
-            -F "id=${{ secrets.POEDITOR_PROJECT_ID }}" \
-            -F "language=$lang" \
-            -F "type=xlf")
-          status=$(echo $response | jq -r '.response.status')
-
-          if [ "$status" == "success" ]; then
-            url=$(echo $response | jq -r '.result.url')
-            if [ -n "$url" ]; then
-              echo "Downloading translations for $lang from $url"
-              curl -s -o src/assets/locale/messages.$lang.xlf $url
-                if [ ! -f "src/assets/locale/messages.$lang.xlf" ]; then
-                  echo "Failed to download translations for $lang"
-                  exit 1
-                fi
-              echo "Downloaded translations for $lang"
-            else
-              echo "No URL found for downloading translations for $lang"
-              exit 1
-            fi
-          else
-            echo "Error exporting translations for $lang: $response"
-            exit 1
-          fi
-
-      - name: Stage changes explicitly
-        run: |
-          echo "Staging updated translation files..."
-          git add -A
-          git status
-          if git diff --cached --quiet; then
-            echo "No changes detected. Exiting."
-            exit 0
-          fi
+          git add src/assets/locale/messages.fr.xlf
           git commit -m "Update translations from POEditor"
 
       - name: Push changes
-        run: git push origin update-translation-message
+        run: git push origin HEAD
 
       - name: Create pull request
         uses: peter-evans/create-pull-request@v5
         with:
-          branch: update-translation-message
+          branch: update-translations-$(date +%Y%m%d%H%M%S)
           base: master
           title: "Update translations from POEditor"
           body: |
